import 'package:card_game_sockets/widgets/playingCard.dart';

List<PlayingCard> deck = [
  const PlayingCard(suit: '♥', value: 'A',),
  const PlayingCard(suit: '♥', value: '2',),
  const PlayingCard(suit: '♥', value: '3',),
  const PlayingCard(suit: '♥', value: '4',),
  const PlayingCard(suit: '♥', value: '5',),
  const PlayingCard(suit: '♥', value: '6',),
  const PlayingCard(suit: '♥', value: '7',),
  const PlayingCard(suit: '♥', value: '8',),
  const PlayingCard(suit: '♥', value: '9',),
  const PlayingCard(suit: '♥', value: '10',),
  const PlayingCard(suit: '♥', value: 'J',),
  const PlayingCard(suit: '♥', value: 'Q',),
  const PlayingCard(suit: '♥', value: 'K',),
  const PlayingCard(suit: '♣', value: 'A',),
  const PlayingCard(suit: '♣', value: '2',),
  const PlayingCard(suit: '♣', value: '3',),
  const PlayingCard(suit: '♣', value: '4',),
  const PlayingCard(suit: '♣', value: '5',),
  const PlayingCard(suit: '♣', value: '6',),
  const PlayingCard(suit: '♣', value: '7',),
  const PlayingCard(suit: '♣', value: '8',),
  const PlayingCard(suit: '♣', value: '9',),
  const PlayingCard(suit: '♣', value: '10',),
  const PlayingCard(suit: '♣', value: 'J',),
  const PlayingCard(suit: '♣', value: 'Q',),
  const PlayingCard(suit: '♣', value: 'K',),
  const PlayingCard(suit: '♠', value: 'A',),
  const PlayingCard(suit: '♠', value: '2',),
  const PlayingCard(suit: '♠', value: '3',),
  const PlayingCard(suit: '♠', value: '4',),
  const PlayingCard(suit: '♠', value: '5',),
  const PlayingCard(suit: '♠', value: '6',),
  const PlayingCard(suit: '♠', value: '7',),
  const PlayingCard(suit: '♠', value: '8',),
  const PlayingCard(suit: '♠', value: '9',),
  const PlayingCard(suit: '♠', value: '10',),
  const PlayingCard(suit: '♠', value: 'J',),
  const PlayingCard(suit: '♠', value: 'Q',),
  const PlayingCard(suit: '♠', value: 'K',),
  const PlayingCard(suit: '♦', value: 'A',),
  const PlayingCard(suit: '♦', value: '2',),
  const PlayingCard(suit: '♦', value: '3',),
  const PlayingCard(suit: '♦', value: '4',),
  const PlayingCard(suit: '♦', value: '5',),
  const PlayingCard(suit: '♦', value: '6',),
  const PlayingCard(suit: '♦', value: '7',),
  const PlayingCard(suit: '♦', value: '8',),
  const PlayingCard(suit: '♦', value: '9',),
  const PlayingCard(suit: '♦', value: '10',),
  const PlayingCard(suit: '♦', value: 'J',),
  const PlayingCard(suit: '♦', value: 'Q',),
  const PlayingCard(suit: '♦', value: 'K',),
  
];
